# This is a basic workflow to help you get started with Actions

name: V8

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ubuntu-16.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Clone source code and alter it
      run: |
        mkdir /opt/temp
        cd /opt/temp/
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
    - name:  Get depends
      run: |
        export PATH=/opt/temp/depot_tools:$PATH
        gclient
        mkdir /opt/temp/v8
        cd /opt/temp/v8/
        fetch v8
        cd v8
        gclient sync
        ./build/install-build-deps.sh
        tools/dev/v8gen.py mips64el.release
        ninja -C out.gn/mips64el.release
    - name:  Zip package
      run: |
        mkdir /opt/out
        sudo cd `ls | find /opt/temp/ -name out.gn`
        sudo tar -cvf /opt/out/out.tar *
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: dep-packages
        path: /opt/out
