name: build

on: 
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-16.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /usr/local/bin/grunt
    - name: Clone source code and alter it
      run: |
        git clone https://github.com/ONLYOFFICE/build_tools.git 
        if [ ! -f build_tools/make.py ] ; then
        echo "build_tools/make.py not found "
        exit 1
        fi
        sed -i '108,$d' build_tools/make.py  #不构建，只把依赖打包
    - name:  Get depends
      run: |
        cd build_tools/tools/linux
        mkdir qt_build
        ./automate.py
    - name : Zip packages
      run: |
        mkdir -p /opt/depens/
        cd ../../../
        rm -rf build_tools
        zip -qr /opt/depens/depens.zip `ls|egrep -v 'build_tools'`
    - name : Upload packages
      run: |
          curl -sL https://git.io/file-transfer | sh 
          ./transfer arp /opt/depens/depens.zip
          
