name: build

on: 
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get install -y python git
    - name: Clone source code
      run: |
        git clone https://github.com/ONLYOFFICE/build_tools.git 
        cd build_tools/tools/linux
        ./automate.py
    - name : zip packages
      run: |
        zip -q -r /opt/depens/depens.zip ../../../`ls *|egrep -v build_tools`
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: depens-packages
        path: /opt/depens
