name: build

on: 
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-16.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /usr/local/bin/grunt
    - name: Clone source code and alter it
      run: |
        git clone --depth=1 https://github.com/ONLYOFFICE/build_tools.git /opt/temp/build_tools
        if [ ! -f /opt/temp/build_tools/make.py ] ; then
        echo "build_tools/make.py not found "
        exit 1
        fi
        sed -i '108,$d' /opt/temp/build_tools/make.py  #不构建，只把依赖打包
    - name:  Get depends
      run: |
        cd /opt/temp/build_tools/tools/linux
        mkdir qt_build
        ./automate.py
    - name : Zip packages
      run: |
        mkdir -p /opt/depens/
        rm -rf /opt/temp/build_tools
        7z a /opt/depens/dep /opt/temp/* -v1920m
    - name : Upload packages
      run: |
          curl -sL https://git.io/file-transfer | sh 
          ./transfer cow /opt/depens/dep.7z*
          
